name: CI for Test

on:
  workflow_dispatch:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Repository
        uses: actions/checkout@v4.1.2

      - name: Create Google Services JSON File
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: |
          echo "$GOOGLE_SERVICES_JSON" > google-services.json.b64
          base64 -d -i google-services.json.b64 > ./app/google-services.json

      - name: Create local.properties file
        run: touch local.properties

      - name: Add Base URL to local.properties file
        run: |
          echo "TUK_BASE_URL=KEY" >> local.properties
          echo "GOOGLE_CLIENT_ID=KEY" >> local.properties
          echo "TUK_SENT_PROPOSAL_URL=KEY" >> local.properties
          echo "TUK_PROPOSALS_URL" >> local.properties
          echo "TUK_INVITE_GATHERING_URL" >> local.properties
          echo "TUK_COMPLETE_PROPOSAL_URL" >> local.properties

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew test
